version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: isaias
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: apiusers
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql