version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'apiusers'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'isaias'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql